name: deploy preview (https://htw-imi-showtime.github.io/preview)

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    if: github.repository == 'htw-imi-showtime/showtime-website'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.114.1'
        extended: true

    - name: Build
      run: |
        ./bin/hugo-temp.sh
        hugo \
          --source hugo-temp \
          --environment production \
          --minify \
          --baseURL "https://htw-imi-showtime.github.io/preview/"
        mv hugo-temp/public public

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.PRODUCTION_PREVIEW_DEPLOY_KEY }}
        external_repository: htw-imi-showtime/preview
        publish_branch: main
