name: HUGO VERSIONS

on:
  push:
    branches: [ main ]

jobs:
  hugo:
    if: github.repository == 'htw-imi-showtime/showtime-website'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hugo-version: [0.111.3, 0.114.1, 0.115.1]
        hugo-environment: [staging, production]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Get Theme
      run: |
        git submodule update --init themes/showtime-theme-2021
  
    - name: Hugo Build
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: ${{ matrix.hugo-version }}
        extended: true

    - name: Build
      run: hugo --minify -e ${{ matrix.hugo-environment }} --buildDrafts
